name: Build and deploy ASP.Net Core app to Azure Web App - Comwell

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore Comwell/WebApp/WebApp.csproj

      - name: Build project
        run: dotnet build Comwell/WebApp/WebApp.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish Comwell/WebApp/WebApp.csproj --configuration Release --output publish --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B96BE5C412AC47F49927E990521151DD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1C0EC4567650472B88683C1C5F15D089 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_91FE1A7810DA4F838444FD18E08400E0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Comwell'
          slot-name: 'Production'
          package: .
